### ISSUE TITLE
Many duplicate MAC address

### ISSUE THREAD

**Issue by sourcerorsupreme** [v-byte-cpu/sx#117]
I'm seeing 100+ IP addresses sharing a Mac address during an ARP scan.

I check my managed switch and those do not appear.

Is this an issue with my network or a problem with the way sx is scanning ARP?

**Comment by v-byte-cpu** [comment]
Hi @sourcerorsupreme  it is hard to say what causes this behavior, try recording all arp packets in wireshark and check

**Comment by sourcerorsupreme** [comment]
@v-byte-cpu Thank you very much. I'll attempt to do so and see whats causing the issue.

I will update this issue within the next few days if it turns out to not be user issue on my part.

**Comment by sourcerorsupreme** [comment]
This is not a problem with sx; however, one of the servers I have is responding with hundreds of MAC addresses it does not have. I am investigating this further as it is a problem on my side.

Thank you again for your guidance in the matter.

**Comment by sourcerorsupreme** [comment]
For anyone else that may experience this issue in the future. Ensure that the systems in your network are not using Proxying ARP as that will cause this issue. You can close this ticket as I've resolved the problem on my end.

Thanks for this great tool, truly appreciate your time.
