### ISSUE TITLE
Instructions how to build under Windows?

### ISSUE THREAD

**Issue by inliquid** [v-byte-cpu/sx#123]
When trying to compile under Windows with regular `go install <...>` there is an error:

```
>go install github.com/v-byte-cpu/sx@latest
go: downloading github.com/v-byte-cpu/sx v0.5.0
go: downloading github.com/google/gopacket v1.1.20-0.20210304165259-20562ffb40f8
go: downloading github.com/spf13/cobra v1.5.0
go: downloading github.com/docker/docker v20.10.7+incompatible
go: downloading github.com/moby/moby v20.10.7+incompatible
go: downloading go.uber.org/zap v1.23.0
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/opencontainers/go-digest v1.0.0
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading github.com/containerd/containerd v1.4.4
go: downloading github.com/Microsoft/go-winio v0.4.16
go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.1
# github.com/v-byte-cpu/sx/command
go\pkg\mod\github.com\v-byte-cpu\sx@v0.5.0\command\root.go:168:56: too many arguments in call to afpacket.NewPacketSource
        have (string, bool)
        want (string)
```

**Comment by v-byte-cpu** [comment]
This bug was fixed in the following PR https://github.com/v-byte-cpu/sx/pull/120. But at the moment windows is not supported. 
I will add windows support in the coming days, because really only the automatic default gateway detection is not supported in windows/macos.

**Comment by inliquid** [comment]
Then please update documentation to reflect which OSes are supported and which not. 

The only mention of Windows in README.md currently is this one:
![изображение](https://user-images.githubusercontent.com/6797881/190861376-ea48d5b6-1133-4a8d-84ae-c1dd224a1508.png)

From which I concluded that Windows is supported.

**Comment by v-byte-cpu** [comment]
It is mentioned in the `platform` badge right below the logo. In the screenshot above Windows is referenced as the scan target machine.

**Comment by inliquid** [comment]
Lol

**Comment by maggie44** [comment]
> This bug was fixed in the following PR #120. But at the moment windows is not supported.
> I will add windows support in the coming days, because really only the automatic default gateway detection is not supported in windows/macos.

@v-byte-cpu, did windows and Mac support get added? I couldn’t see a pull request for it. Or could you outline a bit where there are barriers to support around the gateway detection, it may be something I could try and work out?

**Comment by v-byte-cpu** [comment]
> did windows and Mac support get added?

@maggie0002 not yet

> Or could you outline a bit where there are barriers to support around the gateway detection

we need to implement the following two platform-dependent functions for Windows and Mac:
https://github.com/v-byte-cpu/sx/blob/v0.5.0/pkg/ip/ip_other.go

but I forgot about the most important factor, that it is also necessary to implement the `ReadWriter` interface for reading and writing packets:

https://github.com/v-byte-cpu/sx/blob/045444e7b18d00ab3cdd5b4b936d6362fdb9a6cd/pkg/packet/readwriter.go#L5-L8

It is currently only implemented for Linux, using the [afpacket](https://pkg.go.dev/github.com/google/gopacket@v1.1.19/afpacket) package. And we should definitely create a new implementation using [pcap](https://pkg.go.dev/github.com/google/gopacket@v1.1.19/pcap) package for Windows and MacOS. 

If you want to start working on this, you are welcome.

**Comment by maggie44** [comment]
I had tried a package that used pcap before, thought I would mention it as may be useful here for reference: https://github.com/google/gopacket/blob/master/examples/arpscan/arpscan.go. It needed the libpcap-dev package to work, I'm not sure if there is a way to bundle that or if it would have to be part of the installation steps. 

Networking isn't my strong suit. I may have a go at bringing those two pieces together, but I suspect it would be a bit of a rabbit hole and wouldn't get very far. I may need to sit tight ln this one.
