### ISSUE TITLE
Run on Windows 10?

### ISSUE THREAD

**Issue by davmaz** [v-byte-cpu/sx#58]
From a command prompt (as administrator) 
sx arp 192.168.0.1/24
Error: OS platform is not supported
Usage:
  sx arp [flags] subnet

Examples:
arp 192.168.0.1/24
arp 10.0.0.1

**Comment by v-byte-cpu** [comment]
@davmaz :wave: Only Linux is currently supported. You can try to run it in the docker container, but I have not tested it on a Windows machine
