### ISSUE TITLE
Error: stdin is from a terminal

### ISSUE THREAD

**Issue by 0xE2** [v-byte-cpu/sx#93]
TCP scans are failing with `Error: stdin is from a terminal` exception.

**Environment information:**

- OS: Kali 2021.2
- Console & shell: XFCE TerminalEmulator + zsh
- sx: pre-built binary release (tested on v0.2 & 0.3)

**Some sx snippets I tested with** (I renamed `sx` binary to `sxscanner`, because Kali already has some tool named `sx`):
```
sxscanner tcp fin -p 80 10.10.10.230
sxscanner tcp -p 1-65535 10.10.10.230
```

Issues might be somewhere here: [sx/command/config.go#L288](https://github.com/v-byte-cpu/sx/blob/master/command/config.go#L288), but I don't know Go, so now sure what can cause the issue.

**Comment by v-byte-cpu** [comment]
Hi @0xE2 ! `sx` explicitly reads arp cache from stdin pipe or from file that is described in [TCP scan](https://github.com/v-byte-cpu/sx#tcp-scan) section in readme. `Error: stdin is from a terminal` means that `sx` tool expects arp cache from stdin pipe (that demonstrated in most examples) or from file using `-a` option, but you didn't pass that and as a consequence tty is linked to stdin.

**Comment by 0xE2** [comment]
Oh, I wish I read the docs beforehand :) [v-byte-cpu/sx#tcp-scan](https://github.com/v-byte-cpu/sx#tcp-scan)
Thanks!

However, I have a different issue now, when trying to run `sx arp -i tun0 10.10.10.230`:
`Error: invalid source MAC`

Any clues on how can I can possibly fix this? (Note: tun0 is an openvpn connection)

**Comment by v-byte-cpu** [comment]
vpn network interfaces (openvpn, wireguard etc.) are not supported yet, only physical network interfaces. This is because vpn interfaces require to send IP packets instead of Ethernet frames. I'm still thinking about how to add logic without complicating the code.

**Comment by v-byte-cpu** [comment]
@0xE2 I added support for scanning with vpn interfaces and already tested it on wireguard and openvpn networks. You can try it in the 0.4.0 release.
