### ISSUE TITLE
Error: address family not supported by protocol

### ISSUE THREAD

**Issue by Rashid-Malik** [v-byte-cpu/sx#96]
sx arp 192.168.10.1
Error: address family not supported by protocol
Am I doing something wrong?
Using --iface wifi3 or 192.168.10.1/24 parameters also result in the same error.
I am on WSL Kali.

**Comment by v-byte-cpu** [comment]
Hi @Rashid-Malik I believe this is an error within WSL https://github.com/Microsoft/WSL/issues/2538
